In [2]:
import numpy as np
from numpy import random

In [107]:
a = random.random_integers(1,6)
b = random.random_integers(1,6)
x = random.randint(0,3,size=(a,b))
print x
matrix = x
location = []
for i in range(a):
    for j in range(b):
        if matrix[i][j] == 0:
            location.append((i,j))
print location

[[0 1 0 2]
 [0 0 2 2]
 [1 1 1 0]
 [2 0 2 1]]
[(0, 0), (0, 2), (1, 0), (1, 1), (2, 3), (3, 1)]


In [108]:
def get_kill_num(mode,matrix,location):   
    kill_enermy = {}
    for i in location:
        #n = n+1
        count = 0
        x = i[0]
        y = i[1]
        if mode == 'down':
            while x+1<a and y<b and matrix[x+1][y]!=2:
                if matrix[x+1][y] == 1:
                    count += 1
                x = x+1
            kill_enermy[str(i[0])+','+str(i[1])]= count
        if mode == 'right':
            while x<a and y+1<b and matrix[x][y+1]!=2:
                if matrix[x][y+1] == 1:
                    count += 1
                y = y+1
            kill_enermy[str(i[0])+','+str(i[1])]= count
        if mode == 'left':
            while x>=0 and y-1>=0 and matrix[x][y-1]!=2:
                if matrix[x][y-1] == 1:
                    count += 1
                y = y-1
            kill_enermy[str(i[0])+','+str(i[1])]= count
        if mode == 'up':
            while x-1>=0 and y>=0  and matrix[x-1][y]!=2:
                if matrix[x-1][y] == 1:
                    count += 1
                x = x-1
            kill_enermy[str(i[0])+','+str(i[1])]= count
        
    return kill_enermy


In [109]:
kill_enermy1 = {}
kill_enermy2 = {}
kill_enermy3 = {}
kill_enermy4 = {}
kill_enermy1 = get_kill_num('left',matrix,location)
kill_enermy2 = get_kill_num('up',matrix,location)
kill_enermy3 = get_kill_num('down',matrix,location)
kill_enermy4 = get_kill_num('right',matrix,location)

In [111]:
kill_enermy = {}
for i in location:
    kill_enermy[str(i[0])+','+str(i[1])]=kill_enermy1[str(i[0])+','+str(i[1])]+kill_enermy2[str(i[0])+','+str(i[1])]+kill_enermy3[str(i[0])+','+str(i[1])]+kill_enermy4[str(i[0])+','+str(i[1])]
kill =  sorted(kill_enermy.iteritems(), key=lambda d:d[1], reverse = True)
print '坐标及杀死敌人数量为(TOP3)'
print kill[0],kill[1],kill[2]

坐标及杀死敌人数量为(TOP3)
('2,3', 4) ('0,0', 2) ('3,1', 2)


In [85]:
kill_enermy1 = {}
kill_enermy2 = {}
kill_enermy3 = {}
kill_enermy4 = {}
print matrix
n = 0
print '----------------------下-----------------'
for i in location:
    n = n+1
    count = 0
    x = i[0]
    y = i[1]
    print x,y
    if x+1<a and y<b and matrix[x+1][y]!=2:
        print '(',x+1,y,')','=',matrix[x+1][y]
        if matrix[x+1][y] == 1:
            count += 1
        x = x+1
    print '炸弹',n,'结束，炸死敌人',count,' 人'
    kill_enermy1[str(i[0])+','+str(i[1])]= count

n = 0
print '------------------右------------'
for i in location:
    n = n+1
    count = 0
    x = i[0]
    y = i[1]
    while x<a and y+1<b and matrix[x][y+1]!= 2:
        print '(',x,y+1,')','=',matrix[x][y+1]
        if matrix[x][y+1] == 1:
            count += 1
        y = y+1
        print 'y=',y,'count=',count
    print '炸弹',n,'结束，炸死敌人',count,' 人'
    kill_enermy2[str(i[0])+','+str(i[1])] = count
n = 0
print '------------------左------------'
for i in location:
    n = n+1
    count = 0
    x = i[0]
    y = i[1]
    while y-1>= 0  and matrix[x][y-1]!= 2:
        print '(',x,y-1,')','=',matrix[x][y-1]
        if matrix[x][y-1] == 1:
            count += 1
        y = y-1
        print 'y=',y,'count=',count
    print '炸弹',n,'结束，炸死敌人',count,' 人' 
    kill_enermy3[str(i[0])+','+str(i[1])]= count
n = 0
print '----------------------上-------------------'
for i in location:
    n = n+1
    count = 0
    x = i[0]
    y = i[1]
    while x-1>=0 and matrix[x-1][y]!=2:
        print '(',x-1,y,')','=',matrix[x-1][y]
        if matrix[x-1][y] == 1:
            count += 1
        x = x-1
        print 'x=',x,'count=',count
    print '炸弹',n,'结束，炸死敌人',count,' 人' 
    kill_enermy4[str(i[0])+','+str(i[1])]= count
#print kill_enermy1
#print kill_enermy2
#print kill_enermy3
print kill_enermy4
kill_enermy = {}
for i in location:
    kill_enermy[str(i[0])+','+str(i[1])]=kill_enermy1[str(i[0])+','+str(i[1])]+kill_enermy2[str(i[0])+','+str(i[1])]+kill_enermy3[str(i[0])+','+str(i[1])]+kill_enermy4[str(i[0])+','+str(i[1])]
print kill_enermy
kill =  sorted(kill_enermy.iteritems(), key=lambda d:d[1], reverse = True)
print kill[0]

[[0 1 0 2]
 [0 0 1 2]
 [0 1 2 0]]
----------------------下-----------------
0 0
( 1 0 ) = 0
炸弹 1 结束，炸死敌人 0  人
0 2
( 1 2 ) = 1
炸弹 2 结束，炸死敌人 1  人
1 0
( 2 0 ) = 0
炸弹 3 结束，炸死敌人 0  人
1 1
( 2 1 ) = 1
炸弹 4 结束，炸死敌人 1  人
2 0
炸弹 5 结束，炸死敌人 0  人
2 3
炸弹 6 结束，炸死敌人 0  人
------------------右------------
( 0 1 ) = 1
y= 1 count= 1
( 0 2 ) = 0
y= 2 count= 1
炸弹 1 结束，炸死敌人 1  人
炸弹 2 结束，炸死敌人 0  人
( 1 1 ) = 0
y= 1 count= 0
( 1 2 ) = 1
y= 2 count= 1
炸弹 3 结束，炸死敌人 1  人
( 1 2 ) = 1
y= 2 count= 1
炸弹 4 结束，炸死敌人 1  人
( 2 1 ) = 1
y= 1 count= 1
炸弹 5 结束，炸死敌人 1  人
炸弹 6 结束，炸死敌人 0  人
------------------左------------
炸弹 1 结束，炸死敌人 0  人
( 0 1 ) = 1
y= 1 count= 1
( 0 0 ) = 0
y= 0 count= 1
炸弹 2 结束，炸死敌人 1  人
炸弹 3 结束，炸死敌人 0  人
( 1 0 ) = 0
y= 0 count= 0
炸弹 4 结束，炸死敌人 0  人
炸弹 5 结束，炸死敌人 0  人
炸弹 6 结束，炸死敌人 0  人
----------------------上-------------------
炸弹 1 结束，炸死敌人 0  人
炸弹 2 结束，炸死敌人 0  人
( 0 0 ) = 0
x= 0 count= 0
炸弹 3 结束，炸死敌人 0  人
( 0 1 ) = 1
x= 0 count= 1
炸弹 4 结束，炸死敌人 1  人
( 1 0 ) = 0
x= 1 count= 0
( 0 0 ) = 0
x= 0 count= 0
炸弹 5 结束，炸死敌人